config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :students
  resources :programs
  resources :courses
  resources :projects
  root "pages#home"
end

app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :courses
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :tags
  # has_many :programs, through: :courses
  belongs_to :user
  mount_uploader :image, ImageUploader

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def new
    if current_user.student == nil
      @student = Student.new
    else
      redirect_to root_path
    end
  end

  def edit
    if params[:id] == current_user.student.id.to_s || current_user.admin == true
      @student = Student.find_by(id: params[:id])
    else
      redirect_to root_path
    end
  end

  def show
    @student = Student.find_by(id: params[:id])
    session["student_id"] = @student.id
  end

  def create
    arr = []
    if params["courses"] != nil
      params["courses"].each do |k, v|
        arr.push(v)
      end
    end

    student = Student.new
    student.f_name = student_params["f_name"]
    student.l_name = student_params["l_name"]
    student.gender = student_params["gender"]
    student.email = current_user.email
    student.mobile = student_params["mobile"]
    student.linkedin = student_params["linkedin"]
    student.github_user = student_params["github_user"]
    student.twitter = student_params["twitter"]
    req = Cloudinary::Uploader.upload(student_params["img"])
    student.img = req["url"]
    student.bio = student_params["bio"]
    student.user_id = current_user.id
    student.save

    params["projects"].each do |index, project|
      hash_project = JSON.parse(project)
      name_proj = hash_project["name"]
      url_proj = hash_project["html_url"]
      language_proj = hash_project["language"]
      description_proj = hash_project["description"]
      proj = Project.create(name: name_proj, url: url_proj, language: language_proj, description: description_proj)
      # student = Student.find_by(id: params[:id])
      student.projects << proj
    end

    arr.each do |a|
      course = Course.find_by(name: a)
      student.courses << course
    end

    redirect_to root_path
  end

  def update
    arr = []

    if params["courses"] != nil
      params["courses"].each do |k, v|
        arr.push(v)
      end
    end

    params["projects"].each do |index, project|
      hash_project = JSON.parse(project)
      name_proj = hash_project["name"]
      url_proj = hash_project["html_url"]
      language_proj = hash_project["language"]
      description_proj = hash_project["description"]
      proj = Project.create(name: name_proj, url: url_proj, language: language_proj, description: description_proj)
      student = Student.find_by(id: params[:id])
      student.projects << proj
    end

    student = Student.find_by(id: params[:id])
    student.f_name = student_params["f_name"]
    student.l_name = student_params["l_name"]
    student.gender = student_params["gender"]
    student.email = current_user.email
    student.mobile = student_params["mobile"]
    student.linkedin = student_params["linkedin"]
    student.github_user = student_params["github_user"]
    student.twitter = student_params["twitter"]
    req = Cloudinary::Uploader.upload(student_params["img"])
    student.img = req["url"]
    student.bio = student_params["bio"]
    student.user_id = current_user.id
    student.save
    redirect_to student_path(student)

    student.courses.delete_all
    arr.each do |a|
      course = Course.find_by(name: a)
      student.courses << course
    end
  end

  def index
    @students = Student.all
  end

  private

  def student_params
    params.require(:student).permit(:f_name, :l_name, :gender, :email, :mobile, :linkedin, :github_user, :twitter, :img, :bio)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.erb
<div class="container">
  <h1 style="opacity:0.5">Profile</h1>
  <%= form_for @student do |f| %>
    <form class="needs-validation container">
      <div class="form-row">
        <div class="col-lg-6 col-md-4 mb-3">
          <!-- <label for="validationCustom01">First name</label>-->
          <%= f.label :f_name ,"first name",for:"validationCustom01" %>
          <%= f.text_field :f_name,class:"form-control" ,id:"validationCustom01" ,placeholder:"First name" %>
          <!--        <input type="text" class="form-control" id="validationCustom01" placeholder="First name" value="Mark" required>-->
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-lg-6 col-md-4 mb-3">
          <label for="validationCustom02">Last name</label>
          <%= f.text_field :l_name ,class:"form-control", id:"validationCustom02", placeholder:"Last name" %>
          <!--        <input type="text" class="form-control" id="validationCustom02" placeholder="Last name" value="Otto" required>-->
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-lg-6 col-md-4 mb-3">
          <label for="validationCustomUsername">GitHub Username</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroupPrepend">@</span>
            </div>
            <%= f.text_field :github_user, class:"form-control", id:"validationCustomUsername", placeholder:"GitHub" %>
            <!--        <input type="text" class="form-control" id="validationCustomUsername" placeholder="Username" aria-describedby="inputGroupPrepend" required>-->
            <div class="invalid-feedback">
              Please choose a username.
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-md-12 mb-3">
          <label for="validationCustom02">Image</label>
          <div class="input-group">
            <%= f.file_field :img, class:"custom-file-label form-control", id:"validationCustom02" %>
            <!--        <input type="text" class="form-control" id="validationCustom02" placeholder="Last name" value="Otto" required>-->
          </div>
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="col-lg-6 col-md-4 mb-3">
          <label for="validationCustom03">Gender</label>
          <div class="input-group">
            <div class="form-check">
              <%= f.radio_button :gender,'male' %>
              <%#= radio_button_tag 'gender','male',@gender == 'male',true %>
              <%#= f.radio_button :gender,name:"student[gender]", id:"student[gender]", value:"male" %>
              <!--            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="male" checked>-->
              <label class="form-check-label" for="exampleRadios1">
                Male
              </label>
            </div>
            <div class="form-check">
              <%= f.radio_button :gender,'female' %>
              <%#= radio_button_tag 'gender','female',@gender == 'female' %>
              <%#= radio_button_tag 'student[gender]', c.name, "yes" %>
              <%#= f.radio_button :gender,name:"student[gender]", id:"student[gender]", value:"female" %>
              <!--            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="female" checked>-->
              <label class="form-check-label" for="exampleRadios1">
                Female
              </label>
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-md-4 mb-3">
          <label for="validationCustom02">Mobile</label>
          <%= f.telephone_field :mobile,class:"form-control" , placeholder:"05XXXXXXX",id:"example-tel-input" %>
          <!--        <input type="text" class="form-control" id="validationCustom02" placeholder="Last name" value="Otto" required>-->
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-lg-6 col-md-4 mb-3">
          <label for="validationCustom02">Linkedin</label>
          <%= f.text_field :linkedin,class:"form-control", id:"validationCustom02", placeholder:"Linkedin"  %>
          <!--        <input type="text" class="form-control" id="validationCustom02" placeholder="Last name" value="Otto" required>-->
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-lg-6 col-md-6 mb-3">
          <label for="validationCustom02">Twitter</label>
          <%= f.text_field :twitter ,class:"form-control", id:"validationCustom02", placeholder:"Twitter" %>
          <!--        <input type="text" class="form-control" id="validationCustom02" placeholder="Last name" value="Otto" required>-->
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-lg-6 col-md-6 mb-3">
          <label for="validationCustom02">Bio</label>
          <%= f.text_area :bio,class:"form-control", id:"validationCustom02", placeholder:"Bio" %>
          <!--        <input type="text" class="form-control" id="validationCustom02" placeholder="Last name" value="Otto" required>-->
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-lg-6 col-md-6 mb-3">
          <% i=0 %>
          <% Course.all.each do |c|%>
            <div class=" custom-checkbox">
              <%if c.students.find_by(id:params[:id])%>
                <%= check_box_tag 'courses['+i.to_s+']', c.name, "yes" %>
              <%else%>
                <%= check_box_tag 'courses['+i.to_s+']', c.name %>
              <% end%>
              <% i=i+1%>
              <%= c.name %>
              <br>
            <% end %>
            <!--                <input type="checkbox" class="custom-control-input" id="customCheck1">-->
            <!--                <label class="custom-control-label" for="customCheck1">Check this custom checkbox</label>-->
          </div>
        </div>
      </div>
      <!--  <button class="btn btn-primary" type="submit">Submit form</button>-->
      <button class="btn btn-secondary btn-lg"><%=  f.submit%></button>
    </form>
  <% end %>
</div>
<!-- 
<%# form_for @student do |f| %>
  <p>
    <%# f.label :f_name ,"first name" %>
    <%# f.text_field :f_name %>
  </p>
  <p>

  <%# f.label :l_name ,"last name"%>
  <%# f.text_field :l_name %>
  </p>
  <p>

  <%# f.label :gender %>
  <%# f.text_field :gender %>
  </p>
  <p>

  <%# f.label :email %>
  <%# f.text_field :email %>
  </p>
  <p>

  <%# f.label :mobile %>
  <%# f.text_field :mobile %>
  </p>
  <p>

  <%# f.label :linkedin %>
  <%# f.text_field :linkedin %>
  </p>
  <p>

  <%# f.label :github_user %>
  <%# f.text_field :github_user %>
  </p>
  <p>

  <%# f.label :twitter %>
  <%# f.text_field :twitter %>
  </p>
  <p>

  <%# f.label :img %>
  <%# f.text_field :img %>
  </p>
  <p>

  <%# f.label :bio %>
  <%# f.text_field :bio %>
  </p>

  <%# f.submit %>
<%# end %>
-->

app/views/students/_form.html.erb
<div class="container">
  <h1 style="opacity:0.5">Profile</h1>
  <%= form_for @student do |f| %>
    <form class="needs-validation container">
      <div class="form-row">
        <div class="col-lg-6 col-md-4 mb-3">
          <!-- <label for="validationCustom01">First name</label>-->
          <%= f.label :f_name ,"first name",for:"validationCustom01" %>
          <%= f.text_field :f_name,class:"form-control" ,id:"validationCustom01" ,placeholder:"First name" %>
          <!--        <input type="text" class="form-control" id="validationCustom01" placeholder="First name" value="Mark" required>-->
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-lg-6 col-md-4 mb-3">
          <label for="validationCustom02">Last name</label>
          <%= f.text_field :l_name ,class:"form-control", id:"validationCustom02", placeholder:"Last name" %>
          <!--        <input type="text" class="form-control" id="validationCustom02" placeholder="Last name" value="Otto" required>-->
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-12">
          <label for="validationCustomUsername">GitHub Username</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroupPrepend">@</span>
            </div>
            <%= f.text_field :github_user, class:"form-control", id:"validationCustomUsername", placeholder:"GitHub" %>
            <button id="search">Search</button>
            <!--        <input type="text" class="form-control" id="validationCustomUsername" placeholder="Username" aria-describedby="inputGroupPrepend" required>-->
            <div class="invalid-feedback">
              Please choose a username.
            </div>
            <div class="col-12 hidden " id="showprojects">
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-md-12 mb-3">
          <label for="validationCustom02">Image</label>
          <div class="input-group">
            <%= f.file_field :img, class:"custom-file-label form-control", id:"validationCustom02" %>
            <!--        <input type="text" class="form-control" id="validationCustom02" placeholder="Last name" value="Otto" required>-->
          </div>
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="col-lg-6 col-md-4 mb-3">
          <label for="validationCustom03">Gender</label>
          <div class="input-group">
            <div class="form-check">
              <%= f.radio_button :gender,'male' %>
              <%#= radio_button_tag 'gender','male',@gender == 'male',true %>
              <%#= f.radio_button :gender,name:"student[gender]", id:"student[gender]", value:"male" %>
              <!--            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="male" checked>-->
              <label class="form-check-label" for="exampleRadios1">
                Male
              </label>
            </div>
            <div class="form-check">
              <%= f.radio_button :gender,'female' %>
              <%#= radio_button_tag 'gender','female',@gender == 'female' %>
              <%#= radio_button_tag 'student[gender]', c.name, "yes" %>
              <%#= f.radio_button :gender,name:"student[gender]", id:"student[gender]", value:"female" %>
              <!--            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="female" checked>-->
              <label class="form-check-label" for="exampleRadios1">
                Female
              </label>
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-md-4 mb-3">
          <label for="validationCustom02">Mobile</label>
          <%= f.telephone_field :mobile,class:"form-control" , placeholder:"05XXXXXXX",id:"example-tel-input" %>
          <!--        <input type="text" class="form-control" id="validationCustom02" placeholder="Last name" value="Otto" required>-->
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-lg-6 col-md-4 mb-3">
          <label for="validationCustom02">Linkedin</label>
          <%= f.text_field :linkedin,class:"form-control", id:"validationCustom02", placeholder:"Linkedin"  %>
          <!--        <input type="text" class="form-control" id="validationCustom02" placeholder="Last name" value="Otto" required>-->
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-lg-6 col-md-6 mb-3">
          <label for="validationCustom02">Twitter</label>
          <%= f.text_field :twitter ,class:"form-control", id:"validationCustom02", placeholder:"Twitter" %>
          <!--        <input type="text" class="form-control" id="validationCustom02" placeholder="Last name" value="Otto" required>-->
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-lg-6 col-md-6 mb-3">
          <label for="validationCustom02">Bio</label>
          <%= f.text_area :bio,class:"form-control", id:"validationCustom02", placeholder:"Bio" %>
          <!--        <input type="text" class="form-control" id="validationCustom02" placeholder="Last name" value="Otto" required>-->
          <div class="valid-feedback">
            Looks good!
          </div>
        </div>
        <div class="col-lg-6 col-md-6 mb-3">
          <% i=0 %>
          <% Course.all.each do |c|%>
            <div class=" custom-checkbox">
              <%if c.students.find_by(id:params[:id])%>
                <%= check_box_tag 'courses['+i.to_s+']', c.name, "yes" %>
                <%= c.name %>
                <!--
                <div class="col-12 hidden " id="showprojects2">
                    <div class="form-group">
                    <label for="exampleFormControlSelect2">Example multiple select</label>
                    <select multiple class="form-control" id="exampleFormControlSelect2">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    </select>
                    </div>
                  </div>
-->
              <%else%>
                <%= check_box_tag 'courses['+i.to_s+']', c.name %>
                <%= c.name %>
              <% end%>
              <% i=i+1%>
              <br>
            </div>
          <% end %>
        </div>
      </div>
      <!--  <button class="btn btn-primary" type="submit">Submit form</button>-->
      <button class="btn btn-secondary btn-lg"><%=  f.submit%></button>
    </form>
  <% end %>
</div>
<script>
  var search = document.querySelector('#search');
  var user = document.querySelector("#validationCustomUsername");
  var showProjects = document.querySelector("#showprojects");
  // search.addEventListener("click",function(ev){
  
  // });
  
  search.addEventListener("click",function(ev){
  ev.preventDefault();
  /// URL?
  const baseURL = "https://api.github.com";
  // Method?
  var username = user.value;
  const path = `/users/${username}/repos`;
  //apikey
  const apikey = "40c8482cfa9d0eb69621dd16376a7af904e3bc9a";
  const params = `?access_token=${apikey}`;
  const url = baseURL + path + params;
    if( showProjects.classList.contains('hidden')){
      showProjects.classList.remove('hidden');
    }
    fetch(url)
      .then(r => r.json())
      .then(data => {
  //        <div class="col-lg-6 col-md-6 mb-3">
  //          <%# i=0 %>
  //          <%# Course.all.each do |c|%>
  //            <div class=" custom-checkbox">
  //              <%#if c.students.find_by(id:params[:id])%>
  //                <%# check_box_tag 'courses['+i.to_s+']', c.name, "yes" %>
  //                <%# c.name %>
  //
  //                <div class="col-12 hidden " id="showprojects2">
  //                    <div class="form-group">
  //                    <label for="exampleFormControlSelect2">Example multiple select</label>
  //                    <select multiple class="form-control" id="exampleFormControlSelect2">
  //                    <option>1</option>
  //                    <option>2</option>
  //                    <option>3</option>
  //                    <option>4</option>
  //                    <option>5</option>
  //                    </select>
  //                    </div>
  //                  </div>
  //
  //              <%#else%>
  //                <%#= check_box_tag 'courses['+i.to_s+']', c.name %>
  //                <%#= c.name %>
  //              <%# end%>
  //              <%# i=i+1%>
  //
  //              <br>
  //               </div>
  //            <%# end %>
  //
  //        </div>
  
  
  
        showprojects.innerHTML = "";
        showprojects.innerHTML += '<label for="validationCustomUsername">All Projects</label><br>';
        showprojects.innerHTML += '<span class="border">';
      for(var i = 0 ; i < data.length ; i++){
      checkTags =
  `
  <span class="border mr-3">
  <div class="form-check form-check-inline">
  <input type="checkbox" name='projects[${i}]'  id='project_${i}' value='${JSON.stringify(data[i])}'>
  <label class="form-check-label" for="inlineCheckbox1"> ${data[i].name} </label>
  </div>
  </span>
  `
       showprojects.innerHTML += checkTags;
      }
         showprojects.innerHTML += '</span>';
  
      });
   });
</script>
<!-- 
<%# form_for @student do |f| %>
  <p>
    <%# f.label :f_name ,"first name" %>
    <%# f.text_field :f_name %>
  </p>
  <p>
  <%# f.label :l_name ,"last name"%>
  <%# f.text_field :l_name %>
  </p>
  <p>
  <%# f.label :gender %>
  <%# f.text_field :gender %>
  </p>
  <p>
  <%# f.label :email %>
  <%# f.text_field :email %>
  </p>
  <p>
  <%# f.label :mobile %>
  <%# f.text_field :mobile %>
  </p>
  <p>
  <%# f.label :linkedin %>
  <%# f.text_field :linkedin %>
  </p>
  <p>
  <%# f.label :github_user %>
  <%# f.text_field :github_user %>
  </p>
  <p>
  <%# f.label :twitter %>
  <%# f.text_field :twitter %>
  </p>
  <p>
  <%# f.label :img %>
  <%# f.text_field :img %>
  </p>
  <p>
  <%# f.label :bio %>
  <%# f.text_field :bio %>
  </p>
  <%# f.submit %>
<%# end %>
-->

app/views/students/edit.html.erb
<h1 class="margin_top"></h1>
<%= render 'form' %>

app/views/students/index.html.erb
<h1 class="margin_top"></h1>
<h1>All Students</h1>
<% @students.each do |student| %>
  <p>
    <%= link_to student.f_name+" "+student.l_name, student_path(student) %>
     
  </p>

<% end %>

app/views/students/new.html.erb
<<!-- h1 class="margin_top"></h1>

<%# form_for @student do |f| %>
  <p>
    <%# f.label :f_name ,"first name" %>
    <%# f.text_field :f_name %>
  </p>
  <p>
    <%# f.label :l_name ,"last name"%>
    <%# f.text_field :l_name %>
  </p>
  <p>
    <%# f.label :gender %>
    <%# f.text_field :gender %>
  </p>
  <p>
    <%# f.label :email %>
    <%# f.text_field :email %>
  </p>
  <p>
    <%# f.label :mobile %>
    <%# f.text_field :mobile %>
  </p>
  <p>
    <%# f.label :linkedin %>
    <%# f.text_field :linkedin %>
  </p>
  <p>
    <%# f.label :github_user %>
    <%# f.text_field :github_user %>
  </p>
  <p>
    <%# f.label :twitter %>
    <%# f.text_field :twitter %>
  </p>
  <p>
    <%# f.label :img %>
    <%# f.text_field :img %>
  </p>
  <p>
    <%# f.label :bio %>
    <%# f.text_field :bio %>
  </p>
  <p>Courses :</p>
  <%# i#0 %>
  <%# Course.all.each do |c|%>
    <%# check_box_tag 'courses['+i.to_s+']', c.name %>
    <%# i#i+1%>
    <%# c.name %>
    <br>
  <%# end %>
  <br>
  <br>
  <%# f.submit %>
<%# end %>
-->


<%= render partial:"form" %>

app/views/students/show.html.erb
<h1 class="margin_top"></h1>
<div class="container">
  <!-- START the container-->
  <div class="table-responsive panel">
    <table class="table">
      <tbody>
        <tr>
          <td class="text-success"><i class="fa fa-user"></i> Full Name</td>
          <td><%= @student.f_name %>  <%=@student.l_name %></td>
        </tr>
        <tr>
          <td class="text-success"><i class="fa fa-calendar"></i> User Github</td>
          <td><%= @student.github_user  %></td>
        </tr>
        <tr>
          <td class="text-success"><i class="fa fa-list-ol"></i> Email</td>
          <td><%= @student.email  %></td>
        </tr>
        <tr>
          <td class="text-success"><i class="fa fa-book"></i> Gender</td>
          <td><%= @student.gender  %></td>
        </tr>
        <tr>
          <td class="text-success"><i class="fa fa-group"></i> Mobile</td>
          <td><%= @student.mobile  %></td>
        </tr>
        <tr>
          <td class="text-success"><i class="fa fa-calendar"></i> Linkedin</td>
          <td><%= @student.linkedin  %></td>
        </tr>
        <tr>
          <td class="text-success"><i class="fa fa-calendar"></i> Twitter</td>
          <td><%= @student.twitter  %></td>
        </tr>
        <tr>
          <td class="text-success"><i class="fa fa-calendar"></i> Bio</td>
          <td><%= @student.bio  %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <% if user_signed_in? %>
    <% if current_user.student.id == params[:id].to_i || current_user.admin %>
      <%= link_to "Edit", edit_student_path(@student),class:"btn btn-secondary btn"%>
    <% end %>
  <% else %>
  <% end %>
  <!-- End the container-->
</div>
<hr>
<!-- Start show all project of student-->
<% if user_signed_in? %>
  <% if current_user.student.id == params[:id].to_i  || current_user.admin  %>
    <%= link_to "Add New Project", new_project_path ,class:"btn btn-secondary btn-lg" %>
  <% end %>
<% else %>
<% end %>
<h1 style="text-align:center"> All Projects Of Student</h1>
<br>
<div class="col-md-12">
  <!-- START projects -->
  <div style="width:100%">
    <%#= link_to "Add New programs", new_student_path%>
    <div class="container">
      <div class="row">
        <div class="card-deck">
          <% @student.projects.each do |project|%>
            <div class="card-deck col-lg-3 col-md-4 col-sm-6 margin_button ">
              <div class="card" style="width: 80em;">
                <div class="card-body" >
                  <h5 class="card-title"><%= project.name%></h5>
                  <p class="card-text"><%= project.description%></p>
                  <h6 class="card-subtitle mb-2 text-muted">Language:<%= project.language%></h6>
                  <a href="<%= student_path(project.students.first.id)%>">
                    <h6 class="card-text">By <%= project.students.last.f_name + " " + project.students.last.l_name%></h6>
                  </a>
                </div>
                <div class="card-footer">
                  <a href="<%= project_path(project)%>" class="btn btn-primary">Show</a>
                </div>
              </div>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
  <!-- END projects -->