config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :students
  resources :programs
  resources :courses
  resources :projects
  root "pages#home"
end

app/views/pages/home.html.erb
<main role="main" class="bg-light">
      <div id="myCarousel" class="carousel slide bg-dark" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
          <%= image_tag("s3.jpg", :alt => "rss feed", :class => "first-slide fill_img opacity") %>
            <div class="container">
              <div class="carousel-caption text-left">
                <h1> Helping students help themselves</h1>
                <p></p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
          <%= image_tag("s4.jpg", :alt => "Second slide", class:"second-slide fill_img opacity") %>
            <div class="container">
              <div class="carousel-caption">
                <h1>Being Hungry to Learn</h1>
                <p></p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <%= image_tag("oayt5g0.jpg", :alt => "Third slide", class:"third-slide fill_img opacity") %>
            <div class="container">
              <div class="carousel-caption text-right">
                <h1>We develop relationships that make a positive difference in our students' projects</h1>
                <p></p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <!-- Wrap the rest of the page in another container to center all the content. -->

      <div class="container marketing">
      <!-- START Cards of Programs -->
       <!-- 
       <div class="album py-5 bg-light">
        <div class="container">
        <div class="row">
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
              <%= image_tag("oayt5g0.jpg", :alt => "Third slide", class:"card-img-top") %>
               <div class="card-body">
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
        </div>
        </div>
        -->
     
    <div class="album py-5 bg-light">
    <div class="container">
    <div class="row">
      <div class="card-deck">

       <% if user_signed_in? %>
       <% if current_user.admin %>
       <a href="<%= new_program_path%>" style="display: grid;">
        <button type="button" class="btn btn-sm btn-outline-secondary">Add</button>
        </a>
        <% end%>
        <% end%>
      <% @programs.each do |program| %>
    <!--<a href="<%= program_path(program) %>" ></a>-->
<!--    <div class="col-md-4">-->
    <div class="card mb-4 shadow-sm">
    <img src="<%= program.img %>" class="img-fluid " style="height: 200px;">
    <div class="card-body">
    <h4><%= program.name %></h4>
    <p class="card-text"><%= program.short_description %></p>
    </div>
<div class="card-footer">
    <div class="d-flex justify-content-between align-items-center">
    <div class="btn-group ">
    <a href="<%= program_path(program) %>">
    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
       </a>
      <% if user_signed_in? %>
       <% if current_user.admin %>
       <a href="<%= edit_program_path(program)%>">
        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
        </a>
    <% end %>
      <% else %>
      <% end %>

    </div>
    </div>
</div>
    <!--<small class="text-muted">9 mins</small>-->
    </div>
<!--    </div>-->
    <% end %>
      </div>

    </div>
    </div>
    </div>
 
          <!-- END Cards of Programs -->
          
        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">Our Goals <span class="text-muted">If you believe,you can achieve</span></h2>
            <p class="lead">To organize Misk's projects and make them universally accessible and useful.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" src="https://image.freepik.com/free-vector/workspace-in-cartoon-style_23-2147508020.jpg" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">Our Vision <span class="text-muted">Misk Academy shall become a high-quality thought leader and platform for Leadership, Media and Tech professional education</span></h2>
            <p class="lead">We want Misk Academy to become a leading academy, thought leader when it comes to Leadership development in the Middle East and in building the next generation of makers, innovators in Creative Digital Media and in Technology</p>
          </div>
          <div class="col-md-5 order-md-1">
            <img class="featurette-image img-fluid mx-auto" src="https://image.freepik.com/free-vector/education-connection-concept_23-2147508028.jpg" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">Teamwork <span class="text-muted">proverb</span></h2>
            <p class="lead">"If you want to go fast, go alone. If you want to go far, go together."</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" src="https://image.freepik.com/free-vector/cyber-technology-concept-design_1017-13729.jpg"alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->

      </div><!-- /.container -->


      <!-- FOOTER -->
      <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2017-2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>
    </main>