config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :students
  resources :programs
  resources :courses
  resources :projects
  root "pages#home"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    session[:program_id] = @course.id
  end

  def edit
    @course = Course.find_by(id: params[:id])
  end

  def update
    course = Course.find_by(id: params[:id])
    course.update(course_params)
    redirect_to course_path(course)
  end

  def new
    @course = Course.new
  end

  def create
    



    program_id = session[:program_id]
    program = Program.find_by(id: program_id)
    course = program.courses.create(course_params)
    req = Cloudinary::Uploader.upload(course_params["img"])
    course.img =req["url"]
    course.save
    redirect_to program_path(program)
  end

  def destroy
    course = Course.find_by(id: params[:id])
    course.destroy
    redirect_to courses_path
  end

  private

  def course_params
    params.require(:course).permit(:name, :img, :short_description, :long_description, :duration)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="container">
  <%= form_for @course do |f| %>
  <div class="form-group">
  <label for="exampleFormControlInput1">Name</label>
  <%= f.text_field :name,class:"form-control", id:"exampleFormControlInput1" ,placeholder:"name" %>
  </div>

   <div class="form-group">
    <label for="exampleFormControlInput1">Image</label>
    <%= f.file_field :img %>
   </div>

     <div class="form-group">
    <label for="exampleFormControlTextarea1">Short Description</label>
    <%= f.text_field :short_description,class:"form-control", id:"exampleFormControlInput1" ,placeholder:"Short description" %>
  </div>

    <div class="form-group">
    <label for="exampleFormControlTextarea1">Long Description</label>
     <%= f.text_area :long_description,class:"form-control", id:"exampleFormControlTextarea1" ,placeholder:"Long description" %>
  </div>

  <div class="form-group">
    <label for="exampleFormControlTextarea1">Duration</label>
     <%= f.text_area :duration,class:"form-control", id:"exampleFormControlTextarea1" ,placeholder:"Long description" %>
  </div>

<%= f.submit "Create Course", class:"btn btn-secondary btn-lg"%>
 <% end %>
</div>

<!-- 
<%# <%= form_for @course do |f| %> %>
<div>
<%# <%= f.label :name%> %>
<%# <%= f.text_field :name%> %>
<br/>
<%# <%= f.label :img%> %>
<%# <%= f.file_field  :img%> %>
<br/>
<%# <%= f.label :short_description %> %>
<%# <%= f.text_field :short_description %> %>
<br/>
<%# <%= f.label :long_description %> %>
<%# <%= f.text_field :long_description %> %>
<br/>
<%# <%= f.label :duration %> %>
<%# <%= f.text_field :duration %> %>
<br/>
<%# <%= f.submit %> %>
</div>
<%# <% end %> %>

-->

app/views/courses/edit.html.erb
<h1 class="margin_top">Courses edit</h1>
<%= render partial:"form" %>

app/views/courses/index.html.erb
<h1 >All Courses</h1>
<% @courses.each do |c|%>
<div>
<%= link_to(c.name, course_path(c))%>
</div>
<%end%>
 <% if current_user.admin %>

<%= link_to 'Add New Course', new_course_path %>
    <% end %>

app/views/courses/new.html.erb
<h1 class="margin_top">Courses New</h1>
<%= render partial:"form" %>

app/views/courses/show.html.erb
<div class="d-flex align-items-center flex-column "  style="background-image: url('<%= @course.img %>'); background-repeat: no-repeat;background-size: cover; width: 100%;height: 500px;">
  <section class="text-center">
    <br>
    <h1 class="text-white "> <%=@course.name %></h1>
<!--    <img src="<%# @program.icon %>">-->
    <p class="lead  text-white"> <%=@course.short_description%> </p>
      <p class="lead  text-white"> <%=@course.long_description%> </p>
      <p class="lead  text-white"> <%=@course.duration%> </p>
    <div class="mt-auto p-2">
      <div class="row text-white">
        <div class="col">* Students 220</div>
        <div class="col">* Projects 500</div>
        <div class="w-100"></div>
        <div class="col">* 12 Weeks</div>
        <div class="col">* 7 Course</div>
      </div>
    </div>
  </section>
</div>

<!--<h1 class="margin_top" style="text-align:center">Course<h1>-->
<!--<h3 >Course: <%#=@course.name%></h3>-->
<!--<img src="<%#= @course.img %>">-->

<!--<p>Brief Description: <%#=@course.short_description%></p>-->
<!--<p>Full Description: <%#=@course.long_description%></p>-->
<!--<p>Duration: <%#=@course.duration%></p>-->
<% if user_signed_in? %>
 <% if current_user.admin %>
  <%= link_to 'Edit this Course', edit_course_path %>
  <%= link_to "Delete this Course", course_path(@course), method: :delete %>
    <% end %>
<% else %>
<% end %>


<br>
<ul class="nav nav-tabs " id="myTab" role="tablist">
  <li class="nav-item col-6">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Students</a>
  </li>
  <li class="nav-item col-6">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Projects</a>
  </li>
<!--
  <li class="nav-item">
    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Contact</a>
  </li>
-->
</ul>
      
<div class="modal-body row ">
  
<div class="tab-content container-full" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
   
<div class="col-md-12">
<!-- Your first column here -->
<!-- START studnets -->
  <% if user_signed_in? %>
	 <% if current_user.admin %>

    <%= link_to "Add New student", new_student_path%>
    <% end %>
  <% else %>

  <% end %>

<h1>Students</h1>
    
<div class="container">
<div class="row ">
	<div class="col-lg-12">
		<div class="main-box clearfix">
			<div class="table-responsive">
				<table class="table user-list">
					<thead>
						<tr>
							<th><span>User</span></th>
							<th><span>Bio</span></th>
							<th class="text-center"><span>GitHub</span></th>
							<th><span>Email</span></th>
                            <th><span>Projects</span></th>
<!--							<th>&nbsp;</th>-->
						</tr>
					</thead>
					<tbody>
                        


                        <% @course.students.each do |student|%>
						<tr>
							<td>
							<% if student.img == nil %>
								<img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="">
								<% else %>
								<img src= "<%=student.img%>" alt="">

								<% end %>
								<a href="<%= student_path(student)%>" class="user-link"><%= student.f_name + " " + student.l_name%></a>
								<span class="user-subhead">Gender: <%= student.gender%></span>
							</td>
							<td class="text-center">
								<p><%= student.bio%></p>
							</td>
							<td class="text-center">
                                <a href="<%=student.github_user%>"><%=student.github_user%></a>
							</td>
							<td>
								<a href="#"><%= student.email %></a>
							</td>
                            
                            
                            <td>
                                <a href="<%= student_path(student)%>">
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                <span class="badge badge-primary badge-pill"><%= student.projects.all.count%></span>
                                </li>
                                     </a>
                            </td>
                               
<!--
							<td style="width: 20%;">
								<a href="#" class="table-link">
									<span class="fa-stack">
										<i class="fa fa-square fa-stack-2x"></i>
										<i class="fa fa-search-plus fa-stack-1x fa-inverse"></i>
									</span>
								</a>
								<a href="#" class="table-link">
									<span class="fa-stack">
										<i class="fa fa-square fa-stack-2x"></i>
										<i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
									</span>
								</a>
								<a href="#" class="table-link danger">
									<span class="fa-stack">
										<i class="fa fa-square fa-stack-2x"></i>
										<i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
									</span>
								</a>
							</td>
-->
						</tr>
                        <%end%>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    </div>
    </div>
<div>





</div>
<!-- END studnets -->
</div>
</div>
    
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
<!-- Your second column here -->
<div class="col-md-12">
<!-- START projects -->
<div style="width:100%"> 
<%#= link_to "Add New programs", new_student_path%>
<h1 style="text-align:center">Projects</h1>

<div class="container">
<div class="row">
<div class="card-deck">
<% @course.projects.each do |project|%>
<div class="card-deck col-lg-3 col-md-4 col-sm-6 margin_button ">
<div class="card" style="width: 40em;">
<div class="card-body ">
<h5 class="card-title"><%= project.name%></h5>
<p class="card-text"><%= project.description%></p>
<h6 class="card-subtitle mb-2 text-muted">Language:<%= project.language%></h6>
<a href="<%= student_path(project.students.first.id)%>"><h6 class="card-text">By <%= project.students.last.f_name + " " + project.students.last.l_name%></h6></a>
</div>
<div class="card-footer">
<a href="<%= project_path(project)%>" class="btn btn-primary">Show</a>
</div>
</div>  
</div>    
<%end%>
   </div>
    </div>
        </div>
</div>
    
<!-- END projects -->
</div>
    </div>
<!--  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>-->
</div>
     
</div>

     
    
    
    
    
<!--

        <div class="container">
<div class="row">
	<div class="col-lg-12">
		<div class="main-box clearfix">
			<div class="table-responsive">
				<table class="table user-list">
					<thead>
						<tr>
							<th><span>User</span></th>
							<th><span>Created</span></th>
							<th class="text-center"><span>Status</span></th>
							<th><span>Email</span></th>
							<th>&nbsp;</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="">
								<a href="#" class="user-link">Mila Kunis</a>
								<span class="user-subhead">Admin</span>
							</td>
							<td>
								2013/08/08
							</td>
							<td class="text-center">
								<span class="label label-default">Inactive</span>
							</td>
							<td>
								<a href="#">mila@kunis.com</a>
							</td>
							<td style="width: 20%;">
								<a href="#" class="table-link">
									<span class="fa-stack">
										<i class="fa fa-square fa-stack-2x"></i>
										<i class="fa fa-search-plus fa-stack-1x fa-inverse"></i>
									</span>
								</a>
								<a href="#" class="table-link">
									<span class="fa-stack">
										<i class="fa fa-square fa-stack-2x"></i>
										<i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
									</span>
								</a>
								<a href="#" class="table-link danger">
									<span class="fa-stack">
										<i class="fa fa-square fa-stack-2x"></i>
										<i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
									</span>
								</a>
							</td>
						</tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    </div>
    </div>-->